### ISSUE TITLE
Increase Integration Test Timeout 

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-packagedeployer-template#54]
## Describe the bug
I have seen a few times now that the integration tests fail due to a timeout. I believe this is after all the tests are complete and we are cleaning up the test environment.

## To reproduce

Please see [this](https://capgeminiuk.visualstudio.com/GitHub%20Support/_build/results?buildId=5755&view=logs&j=9a32687b-429c-50d4-318b-6f89a014db07&t=36c021b4-b7aa-5aa2-114b-63cd100c07d2) run as an example.

## Expected behaviour
The integration tests complete without throwing a timeout exception.

## Screenshots
```
##[error][xUnit.net 00:05:16.65]     [Test Class Cleanup Failure (Capgemini.PowerApps.PackageDeployerTemplate.IntegrationTests.PackageTemplateBaseTests)] System.TimeoutException
[xUnit.net 00:05:16.65]       System.TimeoutException : The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
[xUnit.net 00:05:16.65]       ---- System.TimeoutException : The HTTP request to 'https://capdevci.crm11.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.46.1136' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
[xUnit.net 00:05:16.65]       -------- System.Net.WebException : The operation has timed out
[xUnit.net 00:05:16.65]       Stack Trace:
[xUnit.net 00:05:16.65]         
[xUnit.net 00:05:16.65]         Server stack trace: 
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
[xUnit.net 00:05:16.65]            at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
[xUnit.net 00:05:16.65]         
[xUnit.net 00:05:16.65]         Exception rethrown at [0]: 
[xUnit.net 00:05:16.65]            at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Delete(String entityName, Guid id)
[xUnit.net 00:05:16.65]         tests\Capgemini.PowerApps.PackageDeployerTemplate.IntegrationTests\PackageDeployerFixture.cs(110,0): at Capgemini.PowerApps.PackageDeployerTemplate.IntegrationTests.PackageDeployerFixture.<UninstallSolution>b__13_0(Entity solution)
[xUnit.net 00:05:16.65]            at System.Collections.Generic.List`1.ForEach(Action`1 action)
[xUnit.net 00:05:16.65]         tests\Capgemini.PowerApps.PackageDeployerTemplate.IntegrationTests\PackageDeployerFixture.cs(108,0): at Capgemini.PowerApps.PackageDeployerTemplate.IntegrationTests.PackageDeployerFixture.UninstallSolution()
[xUnit.net 00:05:16.65]         tests\Capgemini.PowerApps.PackageDeployerTemplate.IntegrationTests\PackageDeployerFixture.cs(51,0): at Capgemini.PowerApps.PackageDeployerTemplate.IntegrationTests.PackageDeployerFixture.Dispose()
[xUnit.net 00:05:16.65]         ----- Inner Stack Trace -----
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
[xUnit.net 00:05:16.65]         ----- Inner Stack Trace -----
[xUnit.net 00:05:16.65]            at System.Net.HttpWebRequest.GetResponse()
[xUnit.net 00:05:16.65]            at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
```

**Comment by ewingjm** [comment]
Yeah, looks to be timing out during the managed solution uninstall.
